### PR TITLE
[220] Cleanup files after successful run

### LINKED ISSUE #220: Sync job not cleaning up after itself leading to duplicate upload attempts
**Describe the bug**
P2G is not deleting the download/working directories as it should after a successful sync.
See #211 and #214 

**To Reproduce**
1. Launch P2G from the command line (console application, not via docker).  
2. After it runs, observe the download/working/upload directories still have files in them and have not been cleaned up

**Expected behavior**
After a successful sync, the working directories and files should be deleted.

**Logs**
```
***@***.*** peloton-to-garmin]$ dotnet run --project
./src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
Welcome! P2G is starting up...
[20:04:30 DBG] Hosting starting
[20:04:30 DBG] App Version: 2.1.1
[20:04:30 DBG] Operating System: Unix 5.4.17.2136
[20:04:30 DBG] DotNet Runtime: 5.0.13
[20:04:30 INF] Application started. Press Ctrl+C to shut down.
[20:04:30 INF] Hosting environment: Production
[20:04:30 INF] Content root path:
/home/myuser/peloton-to-garmin/src/PelotonToGarminConsole
[20:04:30 DBG] Hosting started
[20:04:31 DBG] Fetching recent workouts page: 0
[20:04:31 DBG] Total workouts found: 10
[20:04:31 DBG] Total workouts found after filtering InProgress and
ExcludeWorkoutTypes: 10
[20:04:31 DBG] Workout e4e3096c83e44dc9bfeef79e0e0e74d1 already downloaded,
skipping.
[20:04:31 DBG] Workout 901f3254bf124ad6aee621897995dfd0 already downloaded,
skipping.
[20:04:31 DBG] Workout c724a524789042f6bed78da82c8acfdf already downloaded,
skipping.
[20:04:31 DBG] Workout a623f514b84c4b44a050d1c74f7b6a6f already downloaded,
skipping.
[20:04:31 DBG] Workout e81f88afa01a4dd789684848395df522 already downloaded,
skipping.
[20:04:31 DBG] Workout 7834f58b7a11411b9a435cd360472a06 already downloaded,
skipping.
[20:04:31 DBG] Workout c9b043ce209f41bb942865a7035aa8f2 already downloaded,
skipping.
[20:04:31 DBG] Workout d76812495a7f46d8b1d7b41a5c538abb already downloaded,
skipping.
[20:04:31 DBG] Workout 0573fef365624e20b2e43d6f5a645090 already downloaded,
skipping.
[20:04:31 DBG] Workout a5cd46fe247543d2aa6d200922e3f7cd already downloaded,
skipping.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 INF] Encoded FIT file
/home/myuser/peloton-to-garmin/src/PelotonToGarminConsole/working/901f3254bf124ad6aee621897995dfd0_20_min_AT's_Ride_to_Greatness-_Game_1_with_Alex_Toussaint.Fit
[20:04:32 INF] Backed up file
./output/fit/901f3254bf124ad6aee621897995dfd0_20_min_AT's_Ride_to_Greatness-_Game_1_with_Alex_Toussaint.Fit
[20:04:32 DBG] Prepped Fit file
./working/upload/901f3254bf124ad6aee621897995dfd0_20_min_AT's_Ride_to_Greatness-_Game_1_with_Alex_Toussaint.Fit
for upload.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 INF] Encoded FIT file
/home/myuser/peloton-to-garmin/src/PelotonToGarminConsole/working/c724a524789042f6bed78da82c8acfdf_5_min_AT's_Ride_to_Greatness-_Warm_Up_with_Alex_Toussaint.Fit
[20:04:32 INF] Backed up file
./output/fit/c724a524789042f6bed78da82c8acfdf_5_min_AT's_Ride_to_Greatness-_Warm_Up_with_Alex_Toussaint.Fit
[20:04:32 DBG] Prepped Fit file
./working/upload/c724a524789042f6bed78da82c8acfdf_5_min_AT's_Ride_to_Greatness-_Warm_Up_with_Alex_Toussaint.Fit
for upload.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 INF] Encoded FIT file
/home/myuser/peloton-to-garmin/src/PelotonToGarminConsole/working/a623f514b84c4b44a050d1c74f7b6a6f_10_min_Warm_Up_Ride_with_Leanne_Hainsby.Fit
[20:04:32 INF] Backed up file
./output/fit/a623f514b84c4b44a050d1c74f7b6a6f_10_min_Warm_Up_Ride_with_Leanne_Hainsby.Fit
[20:04:32 DBG] Prepped Fit file
./working/upload/a623f514b84c4b44a050d1c74f7b6a6f_10_min_Warm_Up_Ride_with_Leanne_Hainsby.Fit
for upload.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 DBG] No incline found.
[20:04:32 INF] Encoded FIT file
/home/myuser/peloton-to-garmin/src/PelotonToGarminConsole/working/e4e3096c83e44dc9bfeef79e0e0e74d1_5_min_AT's_Ride_to_Greatness-_Cool_Down_with_Alex_Toussaint.Fit
[20:04:32 INF] Backed up file
./output/fit/e4e3096c83e44dc9bfeef79e0e0e74d1_5_min_AT's_Ride_to_Greatness-_Cool_Down_with_Alex_Toussaint.Fit
[20:04:32 DBG] Prepped Fit file
./working/upload/e4e3096c83e44dc9bfeef79e0e0e74d1_5_min_AT's_Ride_to_Greatness-_Cool_Down_with_Alex_Toussaint.Fit
for upload.
[20:04:32 INF] Beginning Garmin Upload.
[20:04:32 INF] Uploading to Garmin with the following parameters: gupload
-u **email** -p **password**
"./working/upload/901f3254bf124ad6aee621897995dfd0_20_min_AT's_Ride_to_Greatness-_Game_1_with_Alex_Toussaint.Fit"
"./working/upload/c724a524789042f6bed78da82c8acfdf_5_min_AT's_Ride_to_Greatness-_Warm_Up_with_Alex_Toussaint.Fit"
"./working/upload/a623f514b84c4b44a050d1c74f7b6a6f_10_min_Warm_Up_Ride_with_Leanne_Hainsby.Fit"
"./working/upload/e4e3096c83e44dc9bfeef79e0e0e74d1_5_min_AT's_Ride_to_Greatness-_Cool_Down_with_Alex_Toussaint.Fit"
[20:04:36 INF] DEPRECATION: The OpenSSL being used by this python install
(OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported
version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by
Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020
blocks.

[20:04:36 INF] GUpload: 2022-02-03 20:04:32,921 [INFO] Try to login on
GarminConnect...
2022-02-03 20:04:35,417 [INFO] Logged in as myuser
2022-02-03 20:04:35,584 [INFO] Activity already uploaded 8233927839
<http://voice.google.com/calls?a=nc,%2B18233927839>:
901f3254bf124ad6aee621897995dfd0_20_min_AT's_Ride_to_Greatness-_Game_1_with_Alex_Toussaint.Fit
2022-02-03 20:04:35,715 [INFO] Activity already uploaded 8233927861 :
c724a524789042f6bed78da82c8acfdf_5_min_AT's_Ride_to_Greatness-_Warm_Up_with_Alex_Toussaint.Fit
2022-02-03 20:04:35,882 [INFO] Activity already uploaded 8233927883 :
a623f514b84c4b44a050d1c74f7b6a6f_10_min_Warm_Up_Ride_with_Leanne_Hainsby.Fit
2022-02-03 20:04:36,021 [INFO] Activity already uploaded 8234042767 :
e4e3096c83e44dc9bfeef79e0e0e74d1_5_min_AT's_Ride_to_Greatness-_Cool_Down_with_Alex_Toussaint.Fit
2022-02-03 20:04:36,021 [INFO] All done.
```

**Installation (please complete the following information):**
 - OS: [mac, linux, windows]
 - Method: [source/console]
 - Version: [2.1.1, master, latest]

**Additional context**
Mitigation options:
1. You can manually delete these directories after a sync which should avoid duplicate upload attempts
2. Switch to latest stable release of P2G [here](https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v2.1.0)

### PR DESCRIPTION
**Pull request by philosowaffle**
closes #220 

Changes are generally done, but I still need to actually test them out.

### CODE REVIEW

File: src/Sync/SyncService.cs [hunk 1]
```diff
@@ -12,93 +12,103 @@
...
+				response.Errors.Add(new ErrorResponse() { Message = "Failed to convert workouts to FIT format. Check logs for more details." });
+				return response;
+			}
+
+			try
+			{
+				await _garminUploader.UploadToGarminAsync();
+				response.UploadToGarminSuccess = true;
+				
+				_fileHandler.Cleanup(_config.App.UploadDirectory);
```
Comment (philosowaffle) [inline src/Sync/SyncService.cs:92]: Changes here and lines 60,73,79,99
