### PR TITLE
[208] Null reference when no metrics and trying to generate Distance based laps

### LINKED ISSUE #208: [Bug] Running workout with no metrics, Lap Based Distance, Object reference not set to an instance of an object.
**Describe the bug**
Given a running workout recorded via the app with no speed/hr metrics. If the preferred lap type in the settings is set to `Distance` then an NPE error is thrown when attempting to convert to FIT.

**To Reproduce**

**Expected behavior**
Should not throw and should convert successfully.

**Logs**
```
Object reference not set to an instance of an object.

at Conversion.Converter`1.GetDistanceUnit(String unit) in /build/src/Conversion/IConverter.cs:line 520 at Conversion.FitConverter.GetLapsBasedOnDistance(WorkoutSamples workoutSamples, DateTime startTime, Sport sport, SubSport subSport) in /build/src/Conversion/FitConverter.cs:line 683 at Conversion.FitConverter.GetLaps(PreferredLapType preferredLapType, WorkoutSamples workoutSamples, DateTime startTime, Sport sport, SubSport subSport) in /build/src/Conversion/FitConverter.cs:line 613 at Conversion.FitConverter.Convert(Workout workout, WorkoutSamples workoutSamples) in /build/src/Conversion/FitConverter.cs:line 139 at Conversion.Converter`1.Convert(FileFormat format) in /build/src/Conversion/IConverter.cs:line 96

```

**Installation (please complete the following information):**
 - OS: [linux,]
 - Method: [docker]
 - Version: [latest]

**Additional context**

### PR DESCRIPTION
**Pull request by philosowaffle**
closes #208

### CODE REVIEW

File: src/Conversion/IConverter.cs [hunk 1]
```diff
@@ -513,22 +513,22 @@ protected GarminDeviceInfo GetDeviceInfo()
...
-					return DistanceUnit.Unknown;
-			}
-		}
-	}
-}
+		}
+
+		protected DistanceUnit GetDistanceUnit(string unit)
+		{
+			switch (unit?.ToLower())
```
Comment (philosowaffle) [inline src/Conversion/IConverter.cs:520]: All other changes in this file are spaces->tabs. This line is the only functional change.
